### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by akamech4n** [AlteriaX/skill-resets#1]
I saw your update to fix haymaker reset but when i try use +50% reflect dmg on perf block the reset img dont work properly so i edit and put all haymaker IX IDS 
haymaker = [60900, 60901, 60902, 60930, 60931, 60940, 60941, 60942, 60943, 60947, 60950, 60951, 60952, 60956, 60957, 60960, 60961, 60962, 60966, 60967]
idk its cause of this but when i change talyph in game or log on another character skill reset img show weird icon again

**Comment by AlteriaX** [comment]
Oh I'll try to fix it once I level my Brawler
